import Config

# Configure your database
config :paperform2web, Paperform2web.Repo,
  username: "marcinwalczak",
  password: "",
  hostname: "localhost",
  database: "paperform2web_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :paperform2web, Paperform2webWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LbgZ6bok1nO04/3suCtrG3HpkRxN21spKuJeJIQKyxzhRxBxQCzdTq1lF/WT1c2r",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :paperform2web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure Swoosh mailer for development
config :paperform2web, Paperform2web.Mailer,
  adapter: Swoosh.Adapters.Local

# Configure base URL for email links
config :paperform2web, :base_url, "http://localhost:4000"

# Configure Ollama client
config :paperform2web, :ollama_url, "https://openrouter.ai/api/v1"

# Configure Ollama authentication
# Options: :none, :api_key, :bearer, :basic
config :paperform2web, :ollama_auth, %{
  type: :api_key,
  # For API key auth:
   api_key: ""
  # token: "your-bearer-token",

  # For Basic auth:
  # username: "your-username",
  # password: "your-password"
}

# Configure upload directory
config :paperform2web, :upload_directory, "uploads/"

# Enable debug logging for radio buttons to track rendering issues
config :paperform2web, :debug_radio_buttons, true
